#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=0:30:00

echo "Compute #streamlines, #nodes and average streamlines length and convert AFQ to trk."
#matlab -nosplash -nodisplay -r plot_bar_plots
singularity exec docker://brainlife/mcr:neurodebian1604-r2017a bash -c "./compiled/plot_bar_plots && ./compiled/afqConverter1"
ret=$?
if [ ! $ret -eq 0 ]; then
	echo "Computation failed"
	echo $ret > finished
	exit $ret
fi

subjID=`jq -r '._inputs[0].meta.subject' config.json`
for filename in *output_counts.txt; do mv $filename $subjID'_'$filename; done;
for filename in *output_counts.mat; do mv $filename $subjID'_'$filename; done;
run=`jq -r '.run' config.json`


echo "Compute volume and curvature"
#python compute_volume_and_curvature.py -list tract_name_list.txt; 
singularity exec -e docker://brainlife/dipy:0.14 python ./compute_volume_and_curvature.py -list tract_name_list.txt
if [ -f 'tract_measures.npy' ]; then 
    echo "Table created."
else 
	echo "Table missing."
	exit 1
fi

mv tract_measures.npy $subjID'_'$run'_tract_measures.npy'
echo "Complete"

