#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=0:30:00

## modules
echo "Loading modules"
module unload matlab
module load matlab/2017a
echo "Finished loading modules"

echo "Compute tract measures"
matlab -nosplash -nodisplay -r plot_bar_plots
ret=$?
if [ ! $ret -eq 0 ]; then
	echo "Computation failed"
	echo $ret > finished
	exit $ret
fi

subjID=`jq -r '._inputs[0].meta.subject' config.json`
for filename in *output_counts.txt; do mv $filename $subjID'_'$filename; done;
for filename in *output_counts.mat; do mv $filename $subjID'_'$filename; done;
